local wezterm = require("wezterm")

return {
	key_map_preference = "Physical",
	keys = {
		{ key = "a", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;97~" }) },
		{ key = "b", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;98~" }) },
		{ key = "c", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;99~" }) },
		{ key = "d", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;100~" }) },
		{ key = "e", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;101~" }) },
		{ key = "f", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;102~" }) },
		{ key = "g", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;103~" }) },
		{ key = "h", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;104~" }) },
		{ key = "i", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;105~" }) },
		{ key = "j", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;106~" }) },
		{ key = "k", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;107~" }) },
		{ key = "l", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;108~" }) },
		{ key = "m", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;109~" }) },
		{ key = "n", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;110~" }) },
		{ key = "o", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;111~" }) },
		{ key = "p", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;112~" }) },
		{ key = "q", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;113~" }) },
		{ key = "r", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;114~" }) },
		{ key = "s", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;115~" }) },
		{ key = "t", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;116~" }) },
		{ key = "u", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;117~" }) },
		{ key = "v", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;118~" }) },
		{ key = "w", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;119~" }) },
		{ key = "x", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;120~" }) },
		{ key = "y", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;121~" }) },
		{ key = "z", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;122~" }) },
		{ key = "0", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;48~" }) },
		{ key = "1", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;49~" }) },
		{ key = "2", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;50~" }) },
		{ key = "3", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;51~" }) },
		{ key = "4", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;52~" }) },
		{ key = "5", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;53~" }) },
		{ key = "6", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;54~" }) },
		{ key = "7", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;55~" }) },
		{ key = "8", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;56~" }) },
		{ key = "9", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;57~" }) },
		{ key = "\\", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;92~" }) },
		{ key = "-", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;45~" }) },
		{ key = "/", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;47~" }) },
		{ key = ";", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;59~" }) },
		{ key = ",", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;44~" }) },
		{ key = ".", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;46~" }) },
		{ key = "`", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[27;8;96~" }) },
		{ key = "UpArrow", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[1;8A" }) },
		{ key = "DownArrow", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[1;8B" }) },
		{ key = "RightArrow", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[1;8C" }) },
		{ key = "LeftArrow", mods = "CTRL|SHIFT|ALT", action = wezterm.action({ SendString = "\x1b[1;8D" }) },
		{ key = "z", mods = "CMD|SHIFT", action = wezterm.action.ReloadConfiguration },
	},
}
